BloodAlliance/BloodAlliance/Models/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace BloodAlliance.Models
{
    public class LoginViewModel
    {
        [Required]
        public string Username { get; set; }

        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [Display(Name = "Remember me?")]
        public bool RememberMe { get; set; }
    }
}

BloodAlliance/BloodAlliance/Areas/Identity/Pages/Account/Login.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text.Encodings.Web;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System.Runtime.InteropServices;

namespace BloodAlliance.Areas.Identity.Pages.Account
{
    [AllowAnonymous]
    public class LoginModel : PageModel
    {
        private readonly UserManager<IdentityUser> _userManager;
        private readonly SignInManager<IdentityUser> _signInManager;
        private readonly ILogger<LoginModel> _logger;

        public LoginModel(SignInManager<IdentityUser> signInManager, 
            ILogger<LoginModel> logger,
            UserManager<IdentityUser> userManager)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _logger = logger;
        }

        [BindProperty]
        public InputModel Input { get; set; }

        public IList<AuthenticationScheme> ExternalLogins { get; set; }

        public string ReturnUrl { get; set; }

        [TempData]
        public string ErrorMessage { get; set; }

        public class InputModel
        {
            [Required]
            [EmailAddress]
            public string Email { get; set; }

            [Required]
            [DataType(DataType.Password)]
            public string Password { get; set; }

            [Display(Name = "Remember me?")]
            public bool RememberMe { get; set; }
        }

        public async Task OnGetAsync(string returnUrl = null)
        {
            if (!string.IsNullOrEmpty(ErrorMessage))
            {
                ModelState.AddModelError(string.Empty, ErrorMessage);
            }

            returnUrl = returnUrl ?? Url.Content("~/");

            // Clear the existing external cookie to ensure a clean login process
            await HttpContext.SignOutAsync(IdentityConstants.ExternalScheme);

            ExternalLogins = (await _signInManager.GetExternalAuthenticationSchemesAsync()).ToList();

            ReturnUrl = returnUrl;
        }

        public async Task<IActionResult> OnPostAsync(string returnUrl = null)
        {
            returnUrl = returnUrl ?? Url.Content("~/");


            if (ModelState.IsValid)
            {
                // This doesn't count login failures towards account lockout
                // To enable password failures to trigger account lockout, set lockoutOnFailure: true
                var result = await _signInManager.PasswordSignInAsync(Input.Email, Input.Password, Input.RememberMe, lockoutOnFailure: false);
                var user = await _userManager.FindByEmailAsync(Input.Email);              
                var roles = await _userManager.GetRolesAsync(user);
                if (result.Succeeded)
                {
                    _logger.LogInformation("User logged in.");
                    //return LocalRedirect(returnUrl);
                    foreach (var role in roles)
                    {
                        if (role == "Donor")
                        {
                            returnUrl = Url.Action("Index", "Donor", new { area = ""});
                            returnUrl = returnUrl ?? Url.Content("~/");
                            return LocalRedirect(returnUrl);
                        }

                        
                    }

                    return LocalRedirect(returnUrl);
                }
                /*if (result.RequiresTwoFactor)
                {
                    return RedirectToPage("./LoginWith2fa", new { ReturnUrl = returnUrl, RememberMe = Input.RememberMe });
                }
                if (result.IsLockedOut)
                {
                    _logger.LogWarning("User account locked out.");
                    return RedirectToPage("./Lockout");
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Invalid login attempt.");
                    return Page();
                }*/





            }

            // If we got this far, something failed, redisplay form
            return Page();
        }
    }
}

BloodAlliance/BloodAlliance/Controllers/GostController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace BloodAlliance.Controllers
{
    public class GostController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Test ()
        {

            return View();
        }

        public IActionResult Informacije ()
        {
            return View();
        }
    }
}

BloodAlliance/BloodAlliance/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using BloodAlliance.Models;
using Microsoft.AspNetCore.Identity;
using static BloodAlliance.Areas.Identity.Pages.Account.LoginModel;
using Microsoft.AspNetCore.Routing;

namespace BloodAlliance.Controllers
{
    public class HomeController : Controller
    {

        private readonly ILogger<HomeController> _logger;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly SignInManager<IdentityUser> _signInManager;
        private readonly BAContext _context;

        public HomeController(BAContext context, ILogger<HomeController> logger, UserManager<IdentityUser> userManager, SignInManager<IdentityUser> signInManager)
        {
            _logger = logger;
            _userManager = userManager;
            _signInManager = signInManager;
            _context = context;
        }

        
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]

        public async Task<IActionResult> Login(LoginViewModel model, string returnUrl)
        {
             if(ModelState.IsValid)
            {
                var user = await _userManager.FindByNameAsync(model.Username);
                
                    var result = await _signInManager.PasswordSignInAsync(model.Username, model.Password, model.RememberMe, false);

                    if (result.Succeeded)
                    {

                        var roles = await _userManager.GetRolesAsync(user);


                        foreach (var role in roles)
                        {
                            if (role == "Donor")
                            {
                            
                            Donor donor = _context.Donor.FirstOrDefault(donor => donor.Username == model.Username);
                            statusDonora stariStatus = donor.StatusDonora;

                            donor.PromijeniStatus();
                            _context.Update(donor);



                            if (stariStatus == statusDonora.neMozeDatiKrv && stariStatus != donor.StatusDonora)
                            {
                                ObavijestDonor obavijest = new ObavijestDonor();
                                obavijest.DonorId = donor.DonorId;
                                await _context.ObavijestDonor.AddAsync(obavijest);
                                //await _context.SaveChangesAsync();
                            }
                            await _context.SaveChangesAsync();
                            return RedirectToAction("Donor", new RouteValueDictionary(new { controller = "Donor", action = "Donor", username = donor.Username }));
                            }
                            else if (role == "Administrator")
                            {
                                return RedirectToAction("Index", "Administrator");

                            }
                            else if (role == "Bolnica")
                            {
                                return RedirectToAction("Index", "Bolnica");
                            }
                        }
                    }
                else ModelState.AddModelError(string.Empty, "Invalid Login Attempt");

            }
            else ModelState.AddModelError(string.Empty, "Invalid Login Attempt");

            return View(model);
        }

        
    }
}

BloodAlliance/BloodAlliance/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Index";
}


@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/login.css" />

</head>
<body class="background">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3">
            <div>
                <a style="margin-left: 180px" class="btn btn-outline-danger" asp-area="" asp-controller="Gost" asp-action="Informacije">O nama</a>
                <a style="margin-left:20px" class="btn btn-outline-danger" asp-area="" asp-controller="Home" asp-action="Login">Log In</a>
                <a style="margin-left:20px" class="btn btn-outline-danger" asp-area="" asp-controller="Gost" asp-action="Index">Gost</a>
                <a style="margin-left: 790px" class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><b>Kontakt</b></a>

            </div>
        </nav>
    </header>

    <h1 style="margin-left: 290px; margin-top: 0px; font-size: 180px" class="text-danger"><b>Blood</b></h1>
    <h1  style="margin-left: 145px; margin-top: 45px; font-size: 150px"><b>Alliance</b></h1>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - BloodAlliance - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

</body>
</html>

BloodAlliance/BloodAlliance/Views/Home/Login.cshtml
@model BloodAlliance.Models.LoginViewModel

@{
    ViewData["Title"] = "Login";
}


@{
    Layout = null;
}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HOME</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/login.css" />
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">

    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body  class="container-fluid background">
    <div>
        <div class="row">
            <div class="col-md-4 col-sm-4 col-xs-12"></div>
            <div class="col-md-4 col-sm-4 col-xs-12">
                <section  class="form-container section-background">
                    <h2 style="text-align: center"><b> Log In </b></h2>
                    <hr />
                    <form id="account" method="post">
                        <div asp-validation-summary="All" class="text-danger"></div>
                        <div class="form-group">
                            <label asp-for="Username"></label>
                            <input asp-for="Username" class="form-control" />  
                        </div>
                        <div class="form-group">
                            <label asp-for="Password"></label>
                            <input asp-for="Password" class="form-control" />
                            <span asp-validation-for="Password" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <div class="checkbox">
                                <label asp-for="RememberMe">
                                    <input asp-for="RememberMe" />
                                    @Html.DisplayNameFor(m => m.RememberMe)
                                </label>
                            </div>
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-danger btn-block">Submit</button>
                        </div>
                        <div class="form-group">
                            <p>
                                <a id="forgot-password">Forgot your password?</a>
                            </p>
                        </div>
                    </form>
                </section>

            </div>
            <div class="col-md-4 col-sm-4 col-xs-12"></div>
        </div>
    </div>



    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - BloodAlliance - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
</body>
</html>